AWSTemplateFormatVersion: '2010-09-09'
Description: Temporary EC2 bastion host for Documenso RDS access

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the bastion will reside.

  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet (with auto-assign public IPv4) for the bastion.

  BastionKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 KeyPair for SSH.

  AllowedCidr:
    Type: String
    Description: CIDR allowed for SSH (e.g. 50.218.89.150/32).

  RdsSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: RDS security group that should accept traffic from the bastion.

  AmiId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID to use for bastion (e.g. latest Amazon Linux 2023).

Resources:
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from admin IP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

  AllowBastionToRds:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RdsSecurityGroupId
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref BastionSecurityGroup

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref BastionKeyName
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      ImageId: !Ref AmiId
      IamInstanceProfile: !Ref SsmInstanceProfile
      Tags:
        - Key: Name
          Value: documenso-bastion

  SsmInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SsmRole

  SsmRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

Outputs:
  InstanceId:
    Description: Bastion instance ID
    Value: !Ref BastionInstance
  BastionPublicIP:
    Description: Public IPv4 address of the bastion
    Value: !GetAtt BastionInstance.PublicIp
